In [2]:
import cv2
import g2o
import numpy as np

In [3]:
def to_twist(R, t):
    """Convert a 3x3 rotation matrix and translation vector (shape (3,))
    into a 6D twist coordinate (shape (6,))."""
    r, _ = cv2.Rodrigues(R)
    twist = np.zeros((6,))
    twist[:3] = r.reshape(3,)
    twist[3:] = t.reshape(3,)
    return twist


def from_twist(twist):
    """Convert a 6D twist coordinate (shape (6,)) into a 3x3 rotation matrix
    and translation vector (shape (3,))."""
    r = twist[:3].reshape(3, 1)
    t = twist[3:].reshape(3, 1)
    R, _ = cv2.Rodrigues(r)
    return R, t

In [5]:
pose = np.array([-5.57818750e-04,  6.74815096e-03, -5.28530516e-04, -8.28738584e-01,
 -4.43129790e-02, -5.57878768e-01])
R, t = from_twist(pose)
print(R, t)

[[ 9.99977092e-01  5.26644337e-04  6.74824649e-03]
 [-5.30408568e-04  9.99999705e-01  5.56031166e-04]
 [-6.74795167e-03 -5.59597756e-04  9.99977076e-01]] [[-0.82873858]
 [-0.04431298]
 [-0.55787877]]


In [8]:
se3quat = g2o.SE3Quat(R, np.squeeze(t))

In [13]:
se3quat.translation(), se3quat.rotation() #.toRotationMatrix()

(array([-0.82873858, -0.04431298, -0.55787877]),
 <g2o.Quaternion at 0x7efec5c92b20>)

In [14]:
se3quat.to_minimal_vector()

array([-8.28738584e-01, -4.43129790e-02, -5.57878768e-01, -2.78908839e-04,
        3.37406900e-03, -2.64264750e-04])

In [27]:
R = se3quat.to_homogeneous_matrix()[0:3, 0:3]
t = se3quat.to_homogeneous_matrix()[0:3, 3]
R, t
pose_ = to_twist(R, t)