In [7]:
import pickle
import numpy as np
import g2o

In [8]:
camera_matrix = pickle.load(open("camera_calibration/parameters/ir/camera_matrix.pkl", "rb"))
pose_graph = pickle.load(open("pose_graph.pkl", "rb"))
map_points = pickle.load(open("map_points.pkl", "rb"))
#map_points = map_points.pts_3d

In [9]:
camera_matrix

array([[1.11981664e+03, 0.00000000e+00, 3.21227846e+02],
       [0.00000000e+00, 1.12392668e+03, 2.65048270e+02],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

In [10]:
pose_graph.nodes[0]["pose"]

array([0., 0., 0., 0., 0., 0.])

In [11]:
map_points.pts_3d

array([[  0.5544012 ,  -0.64260791,  11.98360061],
       [  0.87429767,  -2.72028489,  15.60273631],
       [  1.4773444 ,  -0.55696087,  11.7489116 ],
       ...,
       [-10.23164133,   0.49395244,  10.43934858],
       [-13.51357762,   0.62431668,   9.9337444 ],
       [-11.57258562,   1.85675474,  10.07897165]])

In [13]:
map_points.pts_3d.shape

(4632, 3)